### ISSUE TITLE
Issue with starting and stopping a process with the profiler running in same process

### ISSUE THREAD

**Issue by AnthonyDewhirst** [microsoft/ApplicationInsights-Profiler-AspNetCore#218]
This looks like a reoccurrence of [#186](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/issues/186)

**To Reproduce**
Here is the code for a simple repo:
```c#
namespace ProfilerIssue;

public class Tests
{
    [Test]
    public async Task Test1()
    {
        var source = new CancellationTokenSource(TimeSpan.FromSeconds(2));
        await RunTestAsync(source.Token);
    }

    [Test]
    public async Task Test2()
    {
        var source = new CancellationTokenSource(TimeSpan.FromSeconds(2));
        await RunTestAsync(source.Token);
    }

    public async Task RunTestAsync(CancellationToken cancellationToken)
    {
        await Host.CreateDefaultBuilder()
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            })
            .Build()
            .RunAsync(cancellationToken);
    }
}

public class Startup(IConfiguration configuration, IHostEnvironment hostEnvironment)
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddServiceProfiler();
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
    }
}
```
```xml
<Project Sdk="[Microsoft.NET](http://microsoft.net/).Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.Profiler.AspNetCore" Version="2.7.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>
</Project>
```

one tests passes then the other fails.

**Expected behavior**
Both tests should pass

**Additional details*
Granted, this is not a normal usage - but we have gotten here because we are using Grpc test fixtures which boils down to doing the above using steps similar to here [microsoft guide](https://learn.microsoft.com/en-us/aspnet/core/grpc/test-services?view=aspnetcore-8.0)

My guess right now is that the static instance behaviour of Microsoft.ServiceProfiler.Utilities.CurrentProcessProvider
 in
 Assembly: Microsoft.ServiceProfiler.Common.Utilities, Version=2.6.2403.1501, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a captures the process once in the Lazy. And then when the services are configured for the second time, the process is no longer correct.

For now in the test code I have a dirty hack to inject a dispatch proxy in there instead which just returns 1 for the process id on all calls. Had to go this way as the interface is internal :-(

On a complete side note,  Checkmarx is warning of a transitive dependency to Microsoft.IdentityModel.Tokens 6.11.1

**Comment by xiaomi7732** [comment]
Hey @AnthonyDewhirst, I'll take a look at this. Just curious, what is the reason for you to enable the Service Profiler during a test?

**Comment by AnthonyDewhirst** [comment]
Hey,

If you look at the linked code, it's for a grpc test, so you look to the
web project and reference the real startup code. So you get the service as
you normally would. As in, you are pretty much testing the real set up

**Comment by nstayte** [comment]
I am also expericing this issue after upgrading to 2.7.1 from 2.5.3, our integration tests also reference the real Startup class. In the meantime I have left the version at 2.5.3

`
Autofac.Core.DependencyResolutionException : An exception was thrown while activating λ:Microsoft.Extensions.Hosting.IHostedService[] -> ServiceProfiler.EventPipe.Logging.TelemetryTrackerBackgroundService -> Microsoft.ApplicationInsights.Profiler.Core.Logging.TelemetryTracker.
---- Autofac.Core.DependencyResolutionException : An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.ApplicationInsights.Profiler.Core.Logging.IAppInsightsLogger, Microsoft.ServiceProfiler.Utilities.IProcessProvider)' on type 'TelemetryTracker'.
-------- System.Security.Cryptography.CryptographicException : Concurrent operations from multiple threads on this type are not supported.
`

**Comment by xiaomi7732** [comment]
Appending a callstack for the original issue:

```
  Error Message:
   System.InvalidOperationException : No process is associated with this object.
  Stack Trace:
     at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_Id()
   at Microsoft.ServiceProfiler.Utilities.CurrentProcessProvider.get_ProcessId()
   at Microsoft.ApplicationInsights.Profiler.Core.Logging.TelemetryTracker..ctor(IAppInsightsLogger msAILogger, IProcessProvider processIdProvider)
   at InvokeStub_TelemetryTracker..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at ProfilerIssue.Tests.RunTestAsync(CancellationToken cancellationToken) in C:\temp\NUnit\Test.cs:line 21
   at ProfilerIssue.Tests.Test2() in C:\temp\NUnit\Test.cs:line 16
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

```

@nstayte, I am thinking maybe you are encounter a similar but different issue? Do you mind file a new issue for investigation?

At the same time, I'll keep using this issue tracking for the orignial problem.

**Comment by xiaomi7732** [comment]
I have a potential fix for this issue. Reference PR: !567715. I'll post more details later.
