### ISSUE TITLE
Profiler should display helpful error message when certain environment variables aren't set to the right value

### ISSUE THREAD

**Issue by j-zhong-ms** [microsoft/ApplicationInsights-Profiler-AspNetCore#227]
**Describe the bug**
When COMPlus_EnableDiagnostics=0 (and potentially other environment variable) is set, profiler does not display specific error message. Instead it shows Microsoft.Diagnostics.NETCore.Client.ServerNotAvailableException: Process 1 not running compatible .NET runtime.
   at Microsoft.Diagnostics.NETCore.Client.PidIpcEndpoint.GetDefaultAddress()
   at Microsoft.Diagnostics.NETCore.Client.PidIpcEndpoint.Connect(TimeSpan timeout)
   at Microsoft.Diagnostics.NETCore.Client.IpcClient.SendMessageGetContinuation(IpcEndpoint endpoint, IpcMessage message)
   at Microsoft.Diagnostics.NETCore.Client.EventPipeSession.Start(IpcEndpoint endpoint, IEnumerable`1 providers, Boolean requestRundown, Int32 circularBufferMB)
   at Microsoft.Diagnostics.NETCore.Client.DiagnosticsClient.StartEventPipeSession(IEnumerable`1 providers, Boolean requestRundown, Int32 circularBufferMB)
   at Microsoft.ApplicationInsights.Profiler.Core.TraceControls.DiagnosticsClientTraceControl.Enable(String traceFilePath)
   at Microsoft.ApplicationInsights.Profiler.Core.ServiceProfilerProvider.StartServiceProfilerAsync(IProfilerSource source, CancellationToken cancellationToken)
   at Microsoft.ApplicationInsights.Profiler.Core.Orchestration.OrchestratorEventPipe.StartProfilingAsync(SchedulingPolicy policy, CancellationToken cancellationToken)
   at Microsoft.ServiceProfiler.Orchestration.SchedulingPolicy.StartPolicyAsync(CancellationToken cancellationToken)

**To Reproduce**
Set COMPlus_EnableDiagnostics=0 in dockerfile
Run profiler (net8)

**Expected behavior**
Profiler should display a more helpful error message to help identity the issue

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Package version (Microsoft.ApplicationInsights.Profiler.AspNetCore)
 - Application Insights:
You can usually find that info in your `.csproj` file.

**Additional context**

**Comment by xiaomi7732** [comment]
As we discussed offline, let's:
- [ ] Add a link to the FAQ issue;
- [ ] Update the code to give out proper error messages

**Comment by j-zhong-ms** [comment]
In order for profiler to work properly, certain environment variables should be set to 1 (enabled). By default, they are usually set to 1 already. If any of them is set to 0 (disabled), profiler would not be able to start because a ServerNotAvailableException would be thrown from [.NET diagnostics](https://github.com/dotnet/diagnostics/blob/dbaff1df3f0b2a64e1f77f69eb6938c68be915f9/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcTransport.cs#L332) when it initializes the diagnostic port.

Here is the list of such environment variables --
COMPlus_EnableDiagnostics or DOTNET_EnableDiagnostics
COMPlus_EnableDiagnostics_Profiler or DOTNET_EnableDiagnostics_Profiler
COMPlus_EnableDiagnostics_IPC or DOTNET_EnableDiagnostics_IPC

Find more information about these variables [here](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_enablediagnostics)

**Comment by xiaomi7732** [comment]
Fix released: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.7.3-beta1
