### ISSUE TITLE
AppIdNotFoundException on windows, but profiling seems to work.

### ISSUE THREAD

**Issue by AlexKeySmith** [Microsoft/ApplicationInsights-Profiler-AspNetCore#36]
When looking at the diagnostic logs stream on an App Service Plan I see a AppIdNotFoundException , which I'd guess is the app insights instrumentation key?

I'm providing the key via ARM to be an app setting / environment variable with the name:
ApplicationInsights:InstrumentationKey

I did read that `__` should be used rather than `:`. Due to colon not working on all platforms, however the .net core settings provider does support ":" normally.

Interestingly the profiles do appear to be coming through anyway. I was surprised to see the following extension installed which made me wonder if the old profiler has become active somehow
"Application Insights extension for Azure App Service": "2.6.5"

I purposefully removed the extension from ARM and deleted the resource group to clear everything (it's a development environment) as advised that it's unlikely to be compatible: https://github.com/Microsoft/ApplicationInsights-Profiler-AspNetCore/issues/35

```
2019-02-11T11:35:26  Welcome, you are now connected to log-streaming service.
2019-02-11T11:36:21  PID[6036] Information Unpacking resources...
2019-02-11T11:36:21  PID[6036] Information 02-11 11:36:21 Information: Executing Application Insights Profiler agent version 2.4.60711.2 with arguments:
2019-02-11T11:36:21  PID[6036] Information 02-11 11:36:21 Information: Detected an Azure App Service sandbox.
2019-02-11T11:36:21  PID[6036] Information 02-11 11:36:21 Information: Detected an Azure App Service sandbox.
2019-02-11T11:36:21  PID[6036] Information 02-11 11:36:21 Information: Minimum version enabled on machine:
2019-02-11T11:36:21  PID[6036] Information 02-11 11:36:21 Information: Instrumentation key:
2019-02-11T11:36:21  PID[6036] Information 02-11 11:36:21 Information: Application Insights Profiler endpoint: https://agent.azureserviceprofiler.net
2019-02-11T11:36:21  PID[6036] Information 02-11 11:36:21 Information: Application Insights endpoint: default
2019-02-11T11:36:21  PID[6036] Information 02-11 11:36:21 Information: Runtime Environment: Antares
2019-02-11T11:36:21  PID[6036] Information 02-11 11:36:21 Information: Support files: D:\local\Temp\jobs\continuous\ApplicationInsightsProfiler2\naj33tg5.cjh\spsupport
2019-02-11T11:36:22  PID[6036] Information 02-11 11:36:21 Information: Providing usage data (to opt out set the AppSettings ApplicationInsightsProvideUsageTelemetryData with the value "false"): True
2019-02-11T11:36:22  PID[6036] Information 02-11 11:36:21 Information: Engine mode: Immediate
2019-02-11T11:36:22  PID[6036] Information 02-11 11:36:22 Error: Unexpected exception in agent main process. Details: Microsoft.ServiceProfiler.Utilities.AppIdNotFoundException: Unable to find AppId for iKey:
2019-02-11T11:36:22  PID[6036] Information    at Microsoft.ServiceProfiler.Utilities.AppInsightsProfileFetcher.<FetchProfileAsync>d__3.MoveNext()
2019-02-11T11:36:22  PID[6036] Information --- End of stack trace from previous location where exception was thrown ---
2019-02-11T11:36:22  PID[6036] Information    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-02-11T11:36:22  PID[6036] Information    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-02-11T11:36:22  PID[6036] Information    at Microsoft.ServiceProfiler.DiagnosticsAgent.Program.GetApplicationInsightsAppId(String instrumentationKey, String appInsightsEndpoint)
2019-02-11T11:36:22  PID[6036] Information    at Microsoft.ServiceProfiler.DiagnosticsAgent.Program.Main(String[] cmdArgs)
2019-02-11T11:37:23  PID[6036] Information Unpacking resources...
2019-02-11T11:37:24  PID[6036] Information 02-11 11:37:23 Information: Executing Application Insights Profiler agent version 2.4.60711.2 with arguments:
2019-02-11T11:37:24  PID[6036] Information 02-11 11:37:23 Information: Detected an Azure App Service sandbox.
2019-02-11T11:37:24  PID[6036] Information 02-11 11:37:23 Information: Detected an Azure App Service sandbox.
2019-02-11T11:37:24  PID[6036] Information 02-11 11:37:23 Information: Minimum version enabled on machine:
2019-02-11T11:37:24  PID[6036] Information 02-11 11:37:23 Information: Instrumentation key:
2019-02-11T11:37:24  PID[6036] Information 02-11 11:37:23 Information: Application Insights Profiler endpoint: https://agent.azureserviceprofiler.net
2019-02-11T11:37:24  PID[6036] Information 02-11 11:37:23 Information: Application Insights endpoint: default
2019-02-11T11:37:24  PID[6036] Information 02-11 11:37:23 Information: Runtime Environment: Antares
2019-02-11T11:37:24  PID[6036] Information 02-11 11:37:23 Information: Support files: D:\local\Temp\jobs\continuous\ApplicationInsightsProfiler2\naj33tg5.cjh\spsupport
2019-02-11T11:37:24  PID[6036] Information 02-11 11:37:23 Information: Providing usage data (to opt out set the AppSettings ApplicationInsightsProvideUsageTelemetryData with the value "false"): True
2019-02-11T11:37:24  PID[6036] Information 02-11 11:37:23 Information: Engine mode: Immediate
2019-02-11T11:37:24  PID[6036] Information 02-11 11:37:24 Error: Unexpected exception in agent main process. Details: Microsoft.ServiceProfiler.Utilities.AppIdNotFoundException: Unable to find AppId for iKey:
2019-02-11T11:37:24  PID[6036] Information    at Microsoft.ServiceProfiler.Utilities.AppInsightsProfileFetcher.<FetchProfileAsync>d__3.MoveNext()
2019-02-11T11:37:24  PID[6036] Information --- End of stack trace from previous location where exception was thrown ---
2019-02-11T11:37:24  PID[6036] Information    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-02-11T11:37:24  PID[6036] Information    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-02-11T11:37:24  PID[6036] Information    at Microsoft.ServiceProfiler.DiagnosticsAgent.Program.GetApplicationInsightsAppId(String instrumentationKey, String appInsightsEndpoint)
2019-02-11T11:37:24  PID[6036] Information    at Microsoft.ServiceProfiler.DiagnosticsAgent.Program.Main(String[] cmdArgs)
```

**Comment by pharring** [comment]
Yes, the "old" profiler has become active. Those logs are from the ETW-based agent running as a continuous WebJob.

Be advised that the UI in the Portal is unaware of the "new" profiler that you're trying here.

Two things:
1. The instrumentation key being passed to the "old" profiler is blank. That's why you're getting the AppIdNotFoundException and why you're ultimately not getting ETW profiles. The ETW profiler expects to read the instrumentation key from the APPINSIGHTS_INSTRUMENTATIONKEY (with an underscore) app setting. In your case, since you wanted to use the "new" EventPipe-based profiling, the exception isn't a bad thing -- but it's ugly that you're seeing these failures in the logs.

2. You got the ETW-based profiler because the site extension is pre-installed. It lights up when it detects the presence of the App Settings used for profiling. You should be able to disable it by going to the "Application Insights" tab of your web-site in the Portal and setting the "Profiler" to Off. Or manually set the APPINSIGHTS_PROFILERFEATURE_VERSION setting to "disabled". Or look for the profiler's continuous WebJob and disable it. 

On the other hand, you say you are getting profiles, so they would have to be from the "new" profiler -- which is great news.

If you're still stuck, it'll have to wait until @xiaomi7732 gets back from vacation (end of this month).

**Comment by AlexKeySmith** [comment]
Cool thanks @pharring that worked a treat!

I didn't have much luck with APPINSIGHTS_PROFILERFEATURE_VERSION, but it might due to something unreleated.

I composed some powershell to hit the kudu api and popped it onto stackoverlow in case it proves useful for other people if using a release pipeline: https://stackoverflow.com/questions/54668938/removing-the-appinsights-profiler-from-a-app-service-plan/54668939#54668939

Thanks for your help.
