### ISSUE TITLE
Put profiler logs at custom folder location

### ISSUE THREAD

**Issue by dewanymca** [microsoft/ApplicationInsights-Profiler-AspNetCore#94]
We are running our application in non privileged container and marked filesystem as readonly. While running profiler we are seeing below error and i think we are getting into issue because of read only file system, so we want a way to provide a environment variable which specify path where these file can be write. 

fail: ServiceProfiler.EventPipe.Client.ServiceProfilerProvider[0]
      Expected trace validation error.
ServiceProfiler.EventPipe.Client.TraceValidators.ValidateFailedException: [ConvertTraceToEtlxValidator] File /tmp/5f8772ee-176c-4d24-b684-4cc5ec4f0cca.netperf not found.
 ---> System.IO.FileNotFoundException: File /tmp/5f8772ee-176c-4d24-b684-4cc5ec4f0cca.netperf not found.
   --- End of inner exception stack trace ---
   at ServiceProfiler.EventPipe.Client.TraceValidators.ConvertTraceToEtlxValidator.ValidateImp(IEnumerable`1 samples)
   at ServiceProfiler.EventPipe.Client.TraceValidators.TraceValidatorBase.Validate(IEnumerable`1 samples)
   at ServiceProfiler.EventPipe.Client.ServiceProfilerProvider.ValidateSamples(String traceFilePath, List`1 samples)

PLease help

**Comment by xiaomi7732** [comment]
We are hard-coding the temp trace file to be put under %temp%. We will need to provide a way to allow overwriting the trace working folder.

**Comment by xiaomi7732** [comment]
@dewanymca Please checkout [2.1.0-beta5](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.1.0-beta5). Configuration details are documented here: [Configurations](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/blob/master/Configurations.md). Looking for the configuration of `LocalCacheFolder`.

**Comment by xiaomi7732** [comment]
It looks like the uploader needs to be extract to the writable folder too for it to work E2E:

```shell
Locating file path with input: /app/ServiceProfiler/Microsoft.ApplicationInsights.Profiler.Uploader.dll
dbug: ServiceProfiler.EventPipe.Client.UploaderCallers.UploaderLocator[0]
      File uploader is not found. Try the zip file: /app/ServiceProfiler/TraceUpload.zip
dbug: ServiceProfiler.EventPipe.Client.UploaderCallers.UploaderLocator[0]
      Zip file exist. Unzipping . . .
fail: ServiceProfiler.EventPipe.Client.ServiceProfilerProvider[0]
      Unexpected error happens on stopping service profiler.
System.IO.IOException: Read-only file system
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractRelativeToDirectory(ZipArchiveEntry source, String destinationDirectoryName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName, Boolean overwriteFiles)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName)
   at ServiceProfiler.EventPipe.Client.UploaderCallers.UploaderLocator.Locate(String expectedUploaderPath)
   at ServiceProfiler.EventPipe.Client.TraceUploader.TraceUploaderProxy.UploadAsync(DateTimeOffset sessionId, String traceFilePath, String metadataFilePath, Guid dataCube)
   at ServiceProfiler.EventPipe.Client.ServiceProfilerProvider.UploadTraceAsync(PostStopOptions options, Int32 processId)
   at ServiceProfiler.EventPipe.Client.ServiceProfilerProvider.PostStopProcessAsync(PostStopOptions e)
```

**Comment by xiaomi7732** [comment]
Please try this out: 
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.1.0-beta6
It should use the cache folder for unzipping the uploader.

**Comment by xiaomi7732** [comment]
Synced offline. The E2E scenario works with 2.1.0-beta6 and close this issue.
