### ISSUE TITLE
Method not found exception when using environment variable

### ISSUE THREAD

**Issue by LukeRH** [microsoft/ApplicationInsights-Profiler-AspNetCore#96]
Hi,
I get the following exception when adding the environment variable ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.ApplicationInsights.Profiler.AspNetCore:

System.MissingMethodException: 'Method not found: 'Microsoft.AspNetCore.Hosting.IHostingEnvironment Microsoft.AspNetCore.Hosting.WebHostBuilderContext.get_HostingEnvironment()'.'

My Project is a containerised .net core app 3.1 but i can reproduce this without docker.

I have followed the example here https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/tree/master/examples/EnableServiceProfilerCLR2_1

Please could you help?

Thanks
Luke

**Comment by LukeRH** [comment]
Just found an example where the env variable is set to Microsoft.ApplicationInsights.Profiler.HostingStartup30 for .net core 3.1 and it no longer throws the exception. It would be good if this difference in setup was clearer in the documentation.

**Comment by xiaomi7732** [comment]
```shell
Locating file path with input: /app/ServiceProfiler/Microsoft.ApplicationInsights.Profiler.Uploader.dll
dbug: ServiceProfiler.EventPipe.Client.UploaderCallers.UploaderLocator[0]
      File uploader is not found. Try the zip file: /app/ServiceProfiler/TraceUpload.zip
dbug: ServiceProfiler.EventPipe.Client.UploaderCallers.UploaderLocator[0]
      Zip file exist. Unzipping . . .
fail: ServiceProfiler.EventPipe.Client.ServiceProfilerProvider[0]
      Unexpected error happens on stopping service profiler.
System.IO.IOException: Read-only file system
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractRelativeToDirectory(ZipArchiveEntry source, String destinationDirectoryName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName, Boolean overwriteFiles)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName)
   at ServiceProfiler.EventPipe.Client.UploaderCallers.UploaderLocator.Locate(String expectedUploaderPath)
   at ServiceProfiler.EventPipe.Client.TraceUploader.TraceUploaderProxy.UploadAsync(DateTimeOffset sessionId, String traceFilePath, String metadataFilePath, Guid dataCube)
   at ServiceProfiler.EventPipe.Client.ServiceProfilerProvider.UploadTraceAsync(PostStopOptions options, Int32 processId)
   at ServiceProfiler.EventPipe.Client.ServiceProfilerProvider.PostStopProcessAsync(PostStopOptions e)
```
